### ISSUE TITLE
deprecatedPropType may not be working for pcln-modal

### ISSUE THREAD

**Issue by byakimchuk** [priceline/design-system#703] opened 2020-01-02 17:10 UTC
It seems like the uses of deprecatedPropType may be breaking pcln-modal. Upon bumping to 3.0.0, the following error occurs:

```
TypeError: Object(...) is not a function
    at Module../node_modules/pcln-modal/dist/esm/Modal.js 
```

Referring specifically to the following line:
```
bg: Object(pcln_design_system__WEBPACK_IMPORTED_MODULE_6__["deprecatedPropType"])('color')
```

Upon removing references to deprecatedPropType, things seem to work fine.

**Comment by craigpalermo** [comment] 2020-04-03 15:59
@bgyakimchuk I believe the cause of this is that `pcln-modal@3` requires `pcln-design-system@^3` since that's when `deprecatedPropType` was introduced. If that's the case, feel free to close this issue.

**Closed** 2020-04-17 13:56 UTC
